<a href="https://colab.research.google.com/github/PasAlex8019/Python-for-Data-Science/blob/main/Python_6_%D0%A6%D0%B8%D0%BA%D0%BB_for_%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_%D1%81%D0%BE_%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%BE%D0%BC_%D1%87%D0%B8%D1%81%D0%B5%D0%BB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Цикл for, работа со списками чисел**
### Вывод квадратов чисел через while

In [1]:
number = 0
while number <= 10:
  print(number ** 2)
  number += 1

0
1
4
9
16
25
36
49
64
81
100


### Оптимизация через оператор for

In [3]:
for number in 1,2,3,4,5,6,7,8,9,10:
  print(number ** 2)

1
4
9
16
25
36
49
64
81
100


### Вывести квадраты чисел 2,7,5,3,10 в строгом порядке (здесь с циклом while возникнут сложности)

In [4]:
for i in 2,7,5,3,10:
  print(i ** 2)

4
49
25
9
100


###**Задача "Лотерея"**
### 5 билетов: 345,19,87,1020,421
Если число делится на 5 то билет выигрышный

In [13]:
winners = 0
for ticket in 345,19,87,1020,421:
  if ticket % 5 == 0:
    print('Билет выигрышный!', ticket)
    winners += 1
print('Количество победителей', winners)

Билет выигрышный! 345
Билет выигрышный! 1020
Количество победителей 2


##**Практика**

###**Задание 1. Дом для семьи**
Максим написал программу, которая должна определять, подходит ли земельный участок для его семьи или нет. Живут они втроем, вот и условие будет таким же: если количество квадратных метров делится на 3, то участок подходит.

For in meters 100,90,95,87,102:

 if meters % 3 == 1:

   print(meters, 'Подходит')

 else:

   print(meters, 'Не подходит')
   
Скопируйте программу в редактор и исправьте её. Убедитесь, что она работает правильно и решает задачу Максима.

In [14]:
for meters in 100,90,95,87,102:
  if meters % 3 == 0:
    print(meters, 'Подходит')
  else:
    print(meters, 'Не подходит')
   

100 Не подходит
90 Подходит
95 Не подходит
87 Подходит
102 Подходит


**Задание 2. Таблица степеней**

Аркадию для выступления с докладом нужно выучить таблицу степеней для определённых чисел. Правда, память у него работает довольно необычно, и ему проще учить их в нужном ему порядке.

Напишите программу, которая выводит вторую, третью и четвёртую степень для каждого числа в отдельной строке (первая строка - степени для числа 3, вторая строчка - степени для числа 7 и т.д.). Числа: 3,7,5,6,4.

Результат:

9 27 81

49 343 2401

25 125 625

36 216 1296

16 64 256

In [15]:
for degree in 3,7,5,6,4:
  print(degree ** 2, degree ** 3, degree ** 4)

9 27 81
49 343 2401
25 125 625
36 216 1296
16 64 256


**Задача 3. Лотерея 2**

Напишите программу для немного усложнённой версии задачи про выигрышные билеты. Есть заранее известные номера билетов: 345, 19, 87, 1020 и 421 (можете брать свои номера, не стесняйтесь). Теперь, билет считается выигрышным, если номер билета - трёхзначное число и оно делится на 5. Выведете в консоль сообщение для каждого выигрышного билета и количество победителей.

In [34]:
winners = 0
summ = 0
for ticket in 345,19,87,1020,421:
  if (ticket % 3 == 0) and ((ticket // 100) > 0 and (ticket // 100) < 10):
    print('Билет выигрышный!', ticket)
    winners += 1
print('Количество победителей', winners)

    



Билет выигрышный! 345
Количество победителей 1
